<?php

declare( strict_types = 1 );

namespace SecurePress\Tests\Support;

/**
 * Normally generated by `codecept build` from acceptance.suite.yml's enabled
 * modules — hand-written here since that command can't be run in this
 * sandbox (no PHP/Composer). Regenerate with `codecept build` once a real
 * environment exists; this file is safe to overwrite.
 */
class AcceptanceTester extends \Codeception\Actor {
	use _generated\AcceptanceTesterActions;
}
