# Generated by Django 5.2.16 on 2026-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CornucopiaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=10, unique=True)),
                ('suit_code', models.CharField(max_length=10)),
                ('suit_name', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=2)),
                ('is_critical', models.BooleanField(default=False)),
                ('description_en', models.TextField()),
                ('description_pl', models.TextField(blank=True)),
                ('misc_note', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('owasp_refs', models.JSONField(blank=True, default=list)),
                ('mitre_refs', models.JSONField(blank=True, default=list)),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['suit_code'], name='cards_cornu_suit_co_470c96_idx'), models.Index(fields=['edition'], name='cards_cornu_edition_5c3a12_idx')],
            },
        ),
    ]
