# Generated by Django 5.2.16 on 2026-07-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('EQUIVALENT', 'Equivalent'), ('RELATED', 'Related'), ('MAPS_TO', 'Maps To'), ('PARENT_CHILD', 'Parent Child')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='threats.threat')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='threats.threat')),
            ],
        ),
    ]
