# Generated by Django 5.2.16 on 2026-07-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('mitigation_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('DETECTIVE', 'Detective'), ('CORRECTIVE', 'Corrective'), ('COMPENSATING', 'Compensating')], max_length=15)),
                ('effort', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('effectiveness', models.CharField(choices=[('PARTIAL', 'Partial'), ('SIGNIFICANT', 'Significant'), ('FULL', 'Full')], max_length=15)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='cards.cornucopiacard')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('GO', 'Go'), ('SCALA', 'Scala'), ('LUA', 'Lua')], max_length=10)),
                ('sample_type', models.CharField(choices=[('ATTACK_DEMO', 'Attack Demo'), ('DEFENSE', 'Defense')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField()),
                ('framework_hint', models.CharField(blank=True, max_length=100)),
                ('version_note', models.CharField(blank=True, max_length=100)),
                ('mitigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_samples', to='threats.mitigation')),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attack_vector', models.TextField(blank=True)),
                ('attack_surface', models.TextField(blank=True)),
                ('stride', models.CharField(blank=True, max_length=6)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threats', to='frameworks.framework')),
            ],
            options={
                'ordering': ['framework__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='mitigation',
            name='threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='threats.threat'),
        ),
        migrations.CreateModel(
            name='ThreatTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('pl', 'Polski'), ('en', 'English')], max_length=5)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('attack_vector', models.TextField(blank=True)),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='threats.threat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='threat',
            constraint=models.UniqueConstraint(fields=('framework', 'code'), name='uq_threat_framework_code'),
        ),
        migrations.AddConstraint(
            model_name='threattranslation',
            constraint=models.UniqueConstraint(fields=('threat', 'locale'), name='uq_threattranslation_threat_locale'),
        ),
    ]
