-- CppCitadel - Phase 1 seed data
-- Frameworks: OWASP_WEB, OWASP_LLM, MITRE_ATLAS, COMPTIA_SECAI (per PLAN.md Phase 1 checklist)
-- Threat counts here are representative, not exhaustive - full Cornucopia card catalogue
-- (hundreds of cards) and remaining OWASP Top 10 variants land in Phase 6-8.5.

INSERT INTO framework (code, name, version, description, reference_url) VALUES
    ('OWASP_WEB', 'OWASP Top 10', '2021', 'The ten most critical web application security risks.', 'https://owasp.org/Top10/'),
    ('OWASP_LLM', 'OWASP Top 10 for LLM Applications', '2025', 'The ten most critical risks for applications built on large language models and AI agents.', 'https://owasp.org/www-project-top-10-for-large-language-model-applications/'),
    ('MITRE_ATLAS', 'MITRE ATLAS', '4.x', 'Adversary tactics and techniques matrix for AI/ML systems.', 'https://atlas.mitre.org/'),
    ('COMPTIA_SECAI', 'CompTIA SecAI+', '1.0', 'AI-security certification track: AI as attack target and AI as weapon.', 'https://www.comptia.org/');

-- OWASP Top 10 (2021)
INSERT INTO threat (framework_id, code, title, severity, category, description, attack_vector, attack_surface, stride, tags) VALUES
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A01:2021', 'Broken Access Control', 'CRITICAL', 'Access Control', 'Restrictions on what authenticated users are allowed to do are not properly enforced.', 'Cookie/parameter tampering to gain admin rights, forced browsing to unauthorized pages.', 'API endpoints, admin panels, direct object references', 'E', 'access-control,authorization'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A02:2021', 'Cryptographic Failures', 'HIGH', 'Cryptography', 'Sensitive data exposed due to missing or weak encryption, both in transit and at rest.', 'Network sniffing on unencrypted connections, weak cipher downgrade.', 'Data in transit, data at rest, backups', 'I', 'cryptography,data-exposure'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A03:2021', 'Injection', 'CRITICAL', 'Injection', 'Untrusted data sent to an interpreter as part of a command or query.', 'SQL injection, OS command injection, LDAP injection via unsanitized input.', 'Form fields, API request bodies, query parameters', 'T', 'injection,sql-injection'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A04:2021', 'Insecure Design', 'HIGH', 'Design', 'Missing or ineffective security controls at the design stage, not fixable by implementation alone.', 'Business logic abuse that no amount of input validation can patch.', 'Application architecture, business workflows', 'T,E', 'design,threat-modeling'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A05:2021', 'Security Misconfiguration', 'MEDIUM', 'Configuration', 'Missing hardening, default credentials, verbose error messages, unnecessary features enabled.', 'Exploiting default admin credentials, directory listing, stack traces leaking internals.', 'Servers, frameworks, cloud storage, containers', 'I', 'configuration,hardening'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A06:2021', 'Vulnerable and Outdated Components', 'HIGH', 'Supply Chain', 'Using components with known vulnerabilities or that are unsupported/out of date.', 'Exploiting a published CVE in an unpatched dependency.', 'Third-party libraries, frameworks, OS packages', '', 'supply-chain,dependencies'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A07:2021', 'Identification and Authentication Failures', 'HIGH', 'Authentication', 'Weak login, session, or credential-recovery controls letting attackers impersonate users.', 'Credential stuffing, weak password policy, session fixation.', 'Login forms, session tokens, password reset flows', 'S', 'authentication,session-management'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A08:2021', 'Software and Data Integrity Failures', 'HIGH', 'Integrity', 'Code and infrastructure that does not protect against integrity violations, e.g. unsigned updates.', 'Insecure deserialization, tampered CI/CD pipeline, unsigned auto-updates.', 'CI/CD pipelines, serialization boundaries, plugin systems', 'T', 'integrity,deserialization'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A09:2021', 'Security Logging and Monitoring Failures', 'MEDIUM', 'Logging', 'Insufficient logging and monitoring lets breaches go undetected for long periods.', 'Attacker actions leave no audit trail to prove what happened.', 'Application logs, SIEM pipelines, audit trails', 'R', 'logging,monitoring'),
    ((SELECT id FROM framework WHERE code = 'OWASP_WEB'), 'A10:2021', 'Server-Side Request Forgery (SSRF)', 'HIGH', 'SSRF', 'Application fetches a remote resource without validating a user-supplied URL.', 'Attacker-supplied URL causes the server to make requests to internal-only services.', 'URL fetch/webhook features, PDF/image renderers', 'T,I', 'ssrf,network');

-- OWASP Top 10 for LLM Applications (2025)
INSERT INTO threat (framework_id, code, title, severity, category, description, attack_vector, attack_surface, stride, tags) VALUES
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM01:2025', 'Prompt Injection', 'CRITICAL', 'Injection', 'Manipulating the model via crafted input to ignore its original instructions, directly or indirectly via untrusted content it reads.', 'Direct jailbreak in a chat prompt, or instructions hidden in a document/webpage/code comment the model summarizes.', 'Chat input, RAG documents, code comments, web pages', 'S,E', 'prompt-injection,ai-security'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM02:2025', 'Sensitive Information Disclosure', 'HIGH', 'Data Exposure', 'The model leaks confidential data in its responses, from unfiltered inputs, training-data memorization, or missing RBAC.', 'Extraction prompting to recover PII, secrets, or memorized training data.', 'Model outputs, RAG retrieval results', 'I', 'data-exposure,privacy'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM03:2025', 'Supply Chain Vulnerabilities', 'HIGH', 'Supply Chain', 'Building on compromised external components: infected model downloads, malicious packages, compromised data vendors.', 'Downloading a backdoored model from a public hub; pickle-based model files executing code on load.', 'Model registries, package managers, data vendors', '', 'supply-chain,model-security'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM04:2025', 'Data and Model Poisoning', 'CRITICAL', 'Integrity', 'Deliberately injecting flawed, biased, or malicious data into training data or a RAG knowledge base.', 'Seeding a knowledge base with a hidden trigger phrase that bypasses checks.', 'Training pipelines, RAG ingestion, fine-tuning datasets', 'T', 'poisoning,integrity'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM05:2025', 'Improper Output Handling', 'CRITICAL', 'Output Handling', 'Blindly trusting and forwarding LLM-generated output for execution or rendering.', 'Model coaxed into emitting a payload that becomes XSS, SQL injection, or RCE downstream.', 'Generated code execution, HTML rendering of model output', 'T', 'output-handling,xss'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM06:2025', 'Excessive Agency', 'HIGH', 'Agentic', 'An agentic system given more permission or ability to act than it needs.', 'Agent with full DB write access or unattended destructive tool calls.', 'Tool-calling agents, autonomous coding assistants', 'E', 'agentic,excessive-agency'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM07:2025', 'System Prompt Leakage', 'MEDIUM', 'Data Exposure', 'Extracting a model''s hidden system instructions, which often contain business logic or embedded secrets.', 'Prompting the model to repeat or summarize its own instructions.', 'Chat interfaces, system prompt design', 'I', 'prompt-leakage'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM08:2025', 'Vector and Embedding Weaknesses', 'MEDIUM', 'RAG', 'RAG/vector-database-specific flaws: cross-tenant leakage, embedding poisoning, vector-inversion.', 'Querying a shared vector store to reconstruct another tenant''s confidential text.', 'Vector databases, embedding pipelines', 'I', 'rag,vector-database'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM09:2025', 'Misinformation', 'MEDIUM', 'Reliability', 'Models hallucinate fluently and convincingly; blind trust in output leads to real-world mistakes.', 'Confidently wrong output accepted without verification in a legal, financial, or medical context.', 'Any user-facing generative output', '', 'hallucination,overreliance'),
    ((SELECT id FROM framework WHERE code = 'OWASP_LLM'), 'LLM10:2025', 'Unbounded Consumption', 'HIGH', 'Availability', 'Denial-of-service against the model itself via maximal context/token generation, or cost exhaustion.', 'Repetitive huge prompts causing KV-cache exhaustion or a "denial of wallet" billing attack.', 'Model inference endpoints, API gateways', 'D', 'dos,denial-of-wallet');

-- MITRE ATLAS (representative tactics/techniques)
INSERT INTO threat (framework_id, code, title, severity, category, description, attack_vector, attack_surface, stride, tags) VALUES
    ((SELECT id FROM framework WHERE code = 'MITRE_ATLAS'), 'AML.T0010', 'ML Supply Chain Compromise', 'HIGH', 'Initial Access', 'Malicious code injected into an external ML library or a backdoored model published on a public hub.', 'Developer downloads and deploys a poisoned model disguised as a popular tool.', 'Model hubs, ML library dependencies', '', 'initial-access,supply-chain'),
    ((SELECT id FROM framework WHERE code = 'MITRE_ATLAS'), 'AML.T0051', 'Prompt Injection', 'CRITICAL', 'Initial Access', 'Gaining influence over a chatbot or agent''s behavior via crafted natural-language input.', 'Direct chat jailbreak or indirect injection via ingested content.', 'Chatbots, agentic tool-calling systems', '', 'initial-access,prompt-injection'),
    ((SELECT id FROM framework WHERE code = 'MITRE_ATLAS'), 'AML.T0020', 'Poison Training Data', 'CRITICAL', 'ML Attack Staging', 'Imperceptible perturbations added to training images or text to plant a backdoor or bias.', 'Seeding a training set or RAG store with adversarially crafted samples.', 'Training pipelines, data warehouses', '', 'ml-attack-staging,poisoning'),
    ((SELECT id FROM framework WHERE code = 'MITRE_ATLAS'), 'AML.T0043', 'Adversarial Perturbation', 'HIGH', 'Defense Evasion', 'Input modified imperceptibly to humans but decision-flipping for the model.', 'A sticker on a stop sign fooling a self-driving car''s classifier.', 'Computer vision pipelines, classifiers', '', 'defense-evasion,adversarial-ml'),
    ((SELECT id FROM framework WHERE code = 'MITRE_ATLAS'), 'AML.T0024', 'Model Extraction', 'MEDIUM', 'Exfiltration', 'Querying a commercial model millions of times to train a free clone of it.', 'Systematic API querying to reconstruct model behavior or weights.', 'Public inference APIs', '', 'exfiltration,model-theft'),
    ((SELECT id FROM framework WHERE code = 'MITRE_ATLAS'), 'AML.T0029', 'Denial of ML Service', 'MEDIUM', 'Impact', 'Overloading the GPU/TPU infrastructure serving a model to degrade it for legitimate users.', 'Flooding an inference endpoint with expensive, maximal-context requests.', 'GPU/TPU inference infrastructure', '', 'impact,denial-of-service');

-- CompTIA SecAI+ (representative topics from the AI-as-target / AI-as-weapon curriculum)
INSERT INTO threat (framework_id, code, title, severity, category, description, attack_vector, attack_surface, stride, tags) VALUES
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-PI', 'Prompt Injection (exam objective)', 'CRITICAL', 'Interface Attacks', 'Direct and indirect prompt injection as an AI-as-target attack vector, covering chat and RAG surfaces.', 'Malicious instructions in chat input or in retrieved/ingested documents.', 'Chat interfaces, RAG pipelines', '', 'prompt-injection,exam-objective'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-DP', 'Data Poisoning (exam objective)', 'CRITICAL', 'Integrity Attacks', 'Poisoning training data or an MLOps pipeline to manipulate future model behavior.', 'Compromised data vendor or CI/CD pipeline for model training.', 'MLOps pipelines, data warehouses', '', 'poisoning,exam-objective'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-MT', 'Model Theft (exam objective)', 'HIGH', 'Confidentiality Attacks', 'Extracting or cloning proprietary model weights/IP via systematic API querying.', 'High-volume API querying to reconstruct model behavior.', 'Public inference APIs', '', 'model-theft,exam-objective'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-EA', 'Excessive Agency (exam objective)', 'HIGH', 'Interface Attacks', 'Agentic AI systems granted more permission than needed via plugin/tool integration.', 'Plugin or tool-integration vulnerability exploited to exceed intended scope.', 'Plugin/tool integration layers', '', 'excessive-agency,exam-objective'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-MI', 'Membership Inference / Model Inversion', 'MEDIUM', 'Confidentiality Attacks', 'Confidence-score-based privacy attacks that reveal whether specific data was used in training, or reconstruct it.', 'Repeated queries analyzing confidence scores to infer training set membership.', 'Model confidence/probability outputs', '', 'privacy,exam-objective'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-AW', 'AI-Mutating Malware (AI as weapon)', 'HIGH', 'Adversarial Use of AI', 'Polymorphic malware that uses an LLM to rewrite its own signature and evade detection.', 'Attacker uses an LLM to generate signature variants faster than defenses can update.', 'Endpoint detection, antivirus signature databases', '', 'ai-as-weapon,malware'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-DF', 'AI-Powered Phishing and Deepfakes (AI as weapon)', 'HIGH', 'Adversarial Use of AI', 'Mass-personalized phishing with no language tells, and deepfake voice/video for vishing or biometric bypass.', 'LLM-generated personalized lures; synthetic voice/video impersonating an executive.', 'Email, voice/video communication channels', '', 'ai-as-weapon,phishing'),
    ((SELECT id FROM framework WHERE code = 'COMPTIA_SECAI'), 'SECAI-AE', 'Adversarial Examples (exam objective)', 'MEDIUM', 'Integrity Attacks', 'Imperceptible input noise crafted to fool a classifier into a wrong decision.', 'Perturbed input that a human perceives as unchanged but flips model output.', 'Classifiers, computer vision models', '', 'adversarial-ml,exam-objective');
