// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frameworks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFrameworkByCode = `-- name: GetFrameworkByCode :one
SELECT id, code, name, version, description, reference_url
FROM framework
WHERE code = $1
`

func (q *Queries) GetFrameworkByCode(ctx context.Context, code string) (Framework, error) {
	row := q.db.QueryRow(ctx, getFrameworkByCode, code)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.ReferenceUrl,
	)
	return i, err
}

const listFrameworks = `-- name: ListFrameworks :many
SELECT id, code, name, version, description, reference_url
FROM framework
ORDER BY code
`

func (q *Queries) ListFrameworks(ctx context.Context) ([]Framework, error) {
	rows, err := q.db.Query(ctx, listFrameworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Framework
	for rows.Next() {
		var i Framework
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Version,
			&i.Description,
			&i.ReferenceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFramework = `-- name: UpsertFramework :one
INSERT INTO framework (code, name, version, description, reference_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    reference_url = EXCLUDED.reference_url
RETURNING id, code, name, version, description, reference_url
`

type UpsertFrameworkParams struct {
	Code         string
	Name         string
	Version      string
	Description  pgtype.Text
	ReferenceUrl pgtype.Text
}

func (q *Queries) UpsertFramework(ctx context.Context, arg UpsertFrameworkParams) (Framework, error) {
	row := q.db.QueryRow(ctx, upsertFramework,
		arg.Code,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.ReferenceUrl,
	)
	var i Framework
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.ReferenceUrl,
	)
	return i, err
}
