// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CodeSample struct {
	ID            pgtype.UUID
	MitigationID  pgtype.UUID
	Language      string
	SampleType    string
	Title         string
	Description   pgtype.Text
	Code          string
	FrameworkHint pgtype.Text
	VersionNote   pgtype.Text
}

type ContentHash struct {
	ID         pgtype.UUID
	FileName   string
	Sha256Hash string
	VerifiedAt pgtype.Timestamptz
	IsValid    bool
	VerifiedBy string
}

type CornucopiaCard struct {
	ID            pgtype.UUID
	CardID        string
	SuitCode      string
	SuitName      string
	Edition       string
	Value         string
	IsCritical    bool
	CardKind      string
	Severity      pgtype.Text
	DescriptionEn pgtype.Text
	DescriptionPl pgtype.Text
	MiscNote      pgtype.Text
	SourceUrl     pgtype.Text
	OwaspRefs     pgtype.Text
	MitreRefs     pgtype.Text
	ContentSha256 pgtype.Text
}

type CrossReference struct {
	ID               pgtype.UUID
	SourceThreatID   pgtype.UUID
	TargetThreatID   pgtype.UUID
	RelationshipType string
	Description      pgtype.Text
}

type Framework struct {
	ID           pgtype.UUID
	Code         string
	Name         string
	Version      string
	Description  pgtype.Text
	ReferenceUrl pgtype.Text
}

type Mitigation struct {
	ID             pgtype.UUID
	ThreatID       pgtype.UUID
	CardID         pgtype.UUID
	Title          string
	Description    pgtype.Text
	MitigationType string
	Effort         string
	Effectiveness  string
}

type Threat struct {
	ID            pgtype.UUID
	FrameworkID   pgtype.UUID
	Code          string
	Title         string
	Severity      string
	Category      string
	Description   string
	AttackVector  string
	AttackSurface string
	Stride        string
	CveReferences string
	Tags          string
}

type ThreatTranslation struct {
	ID           pgtype.UUID
	ThreatID     pgtype.UUID
	Locale       string
	Title        string
	Description  pgtype.Text
	AttackVector pgtype.Text
}
