// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetFrameworkByCode(ctx context.Context, code string) (Framework, error)
	GetThreatByID(ctx context.Context, id pgtype.UUID) (GetThreatByIDRow, error)
	ListFrameworks(ctx context.Context) ([]Framework, error)
	// D-02: this is the entire optional-filter surface for GET /api/v1/threats
	// as ONE statically-checked query - sqlc.narg() makes each filter nullable
	// at the parameter level, so there is no runtime query builder and no
	// string-concatenation path, satisfying the same guarantee app04_scala_react
	// gets from ZIO Quill's macros.
	SearchThreats(ctx context.Context, arg SearchThreatsParams) ([]SearchThreatsRow, error)
	UpsertFramework(ctx context.Context, arg UpsertFrameworkParams) (Framework, error)
	UpsertThreat(ctx context.Context, arg UpsertThreatParams) error
}

var _ Querier = (*Queries)(nil)
