// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threats.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getThreatByID = `-- name: GetThreatByID :one
SELECT t.id, t.framework_id, t.code, t.title, t.severity, t.category,
       t.description, t.attack_vector, t.attack_surface, t.stride,
       t.cve_references, t.tags, f.code AS framework_code, f.name AS framework_name
FROM threat t
JOIN framework f ON f.id = t.framework_id
WHERE t.id = $1
`

type GetThreatByIDRow struct {
	ID            pgtype.UUID
	FrameworkID   pgtype.UUID
	Code          string
	Title         string
	Severity      string
	Category      string
	Description   string
	AttackVector  string
	AttackSurface string
	Stride        string
	CveReferences string
	Tags          string
	FrameworkCode string
	FrameworkName string
}

func (q *Queries) GetThreatByID(ctx context.Context, id pgtype.UUID) (GetThreatByIDRow, error) {
	row := q.db.QueryRow(ctx, getThreatByID, id)
	var i GetThreatByIDRow
	err := row.Scan(
		&i.ID,
		&i.FrameworkID,
		&i.Code,
		&i.Title,
		&i.Severity,
		&i.Category,
		&i.Description,
		&i.AttackVector,
		&i.AttackSurface,
		&i.Stride,
		&i.CveReferences,
		&i.Tags,
		&i.FrameworkCode,
		&i.FrameworkName,
	)
	return i, err
}

const searchThreats = `-- name: SearchThreats :many
SELECT t.id, t.framework_id, t.code, t.title, t.severity, t.category,
       t.description, t.attack_vector, t.attack_surface, t.stride,
       t.cve_references, t.tags, f.code AS framework_code
FROM threat t
JOIN framework f ON f.id = t.framework_id
WHERE ($1::text IS NULL OR f.code = $1::text)
  AND ($2::text IS NULL OR t.severity = $2::text)
  AND ($3::text IS NULL OR t.stride ILIKE '%' || $3::text || '%')
  AND ($4::text IS NULL OR t.category = $4::text)
  AND ($5::text IS NULL OR t.tags ILIKE '%' || $5::text || '%')
  AND (
    $6::text IS NULL
    OR t.title ILIKE '%' || $6::text || '%'
    OR t.description ILIKE '%' || $6::text || '%'
  )
ORDER BY f.code, t.code
`

type SearchThreatsParams struct {
	FrameworkCode pgtype.Text
	Severity      pgtype.Text
	Stride        pgtype.Text
	Category      pgtype.Text
	Tag           pgtype.Text
	Q             pgtype.Text
}

type SearchThreatsRow struct {
	ID            pgtype.UUID
	FrameworkID   pgtype.UUID
	Code          string
	Title         string
	Severity      string
	Category      string
	Description   string
	AttackVector  string
	AttackSurface string
	Stride        string
	CveReferences string
	Tags          string
	FrameworkCode string
}

// D-02: this is the entire optional-filter surface for GET /api/v1/threats
// as ONE statically-checked query - sqlc.narg() makes each filter nullable
// at the parameter level, so there is no runtime query builder and no
// string-concatenation path, satisfying the same guarantee app04_scala_react
// gets from ZIO Quill's macros.
func (q *Queries) SearchThreats(ctx context.Context, arg SearchThreatsParams) ([]SearchThreatsRow, error) {
	rows, err := q.db.Query(ctx, searchThreats,
		arg.FrameworkCode,
		arg.Severity,
		arg.Stride,
		arg.Category,
		arg.Tag,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchThreatsRow
	for rows.Next() {
		var i SearchThreatsRow
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkID,
			&i.Code,
			&i.Title,
			&i.Severity,
			&i.Category,
			&i.Description,
			&i.AttackVector,
			&i.AttackSurface,
			&i.Stride,
			&i.CveReferences,
			&i.Tags,
			&i.FrameworkCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertThreat = `-- name: UpsertThreat :exec
INSERT INTO threat (framework_id, code, title, severity, category, description, attack_vector, attack_surface, stride, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (framework_id, code) DO UPDATE SET
    title = EXCLUDED.title,
    severity = EXCLUDED.severity,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    attack_vector = EXCLUDED.attack_vector,
    attack_surface = EXCLUDED.attack_surface,
    stride = EXCLUDED.stride,
    tags = EXCLUDED.tags
`

type UpsertThreatParams struct {
	FrameworkID   pgtype.UUID
	Code          string
	Title         string
	Severity      string
	Category      string
	Description   string
	AttackVector  string
	AttackSurface string
	Stride        string
	Tags          string
}

func (q *Queries) UpsertThreat(ctx context.Context, arg UpsertThreatParams) error {
	_, err := q.db.Exec(ctx, upsertThreat,
		arg.FrameworkID,
		arg.Code,
		arg.Title,
		arg.Severity,
		arg.Category,
		arg.Description,
		arg.AttackVector,
		arg.AttackSurface,
		arg.Stride,
		arg.Tags,
	)
	return err
}
