# Generated by Django 5.2.16 on 2026-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
