// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharpGuard.Api.Data;

#nullable disable

namespace SharpGuard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710223710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharpGuard.Api.Entities.Framework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reference_url");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("framework", (string)null);
                });

            modelBuilder.Entity("SharpGuard.Api.Entities.Threat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttackSurface")
                        .HasColumnType("text")
                        .HasColumnName("attack_surface");

                    b.Property<string>("AttackVector")
                        .HasColumnType("text")
                        .HasColumnName("attack_vector");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("CveReferences")
                        .HasColumnType("text")
                        .HasColumnName("cve_references");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uuid")
                        .HasColumnName("framework_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Stride")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stride");

                    b.Property<string>("Tags")
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("Severity");

                    b.HasIndex("FrameworkId", "Code")
                        .IsUnique();

                    b.ToTable("threat", (string)null);
                });

            modelBuilder.Entity("SharpGuard.Api.Entities.Threat", b =>
                {
                    b.HasOne("SharpGuard.Api.Entities.Framework", "Framework")
                        .WithMany("Threats")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("SharpGuard.Api.Entities.Framework", b =>
                {
                    b.Navigation("Threats");
                });
#pragma warning restore 612, 618
        }
    }
}
